site/lib/site_web/router.ex
defmodule SiteWeb.Router do
  use SiteWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SiteWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SiteWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create] # have not implemented logout function
  end

  # Other scopes may use custom stacks.
  # scope "/api", SiteWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SiteWeb.Telemetry
    end
  end
end

site/lib/site/accounts.ex
defmodule Site.Accounts do
    alias Site.Accounts.User;
    alias Site.Repo

    def change_user(%User{} = user) do
        User.changeset(user, %{})
    end

    def create_user(attrs \\ %{}) do
        %User{}
        |> User.changeset(attrs)
        |> Repo.insert()
    end

    def registration_changeset(%User{} = user, params) do
        User.registration_changeset(user, params)
    end

    def register_user(attrs \\ %{}) do
        %User{}
        |> User.registration_changeset(attrs)
        |> Repo.insert()
    end

    def get_user(id) do
        Repo.get(User, id)
    end

    def get_user!(id) do
        Repo.get!(User, id)     
    end

    def get_user_by(params) do
        Repo.get_by(User,params)
    end

    def list_users do
        Repo.all(User)
    end

    def authenticate_by_userphrase_and_passphrase(userphrase, passphrase) do
        user = get_user_by(userphrase: userphrase)

        cond do
            user && Pbkdf2.verify_pass(passphrase, user.password_hash) ->
                {:ok, user}
            
            user ->
                {:error, :unauthorized}

            true ->
                Pbkdf2.no_user_verify()
                {:error, :not_found}
        end
    end

end

site/lib/site/accounts/user.ex
defmodule Site.Accounts.User do
    use Ecto.Schema
    import Ecto.Changeset

    schema "users" do
        field :userphrase, :string
        field :password, :string, virtual: true
        field :password_hash, :string

        timestamps()
    end

    def changeset(user, attrs) do
        user
        |> cast(attrs, [:userphrase])
        |> validate_required([:userphrase])
        |> validate_length(:userphrase, min: 1, max: 254)
        |> unique_constraint(:userphrase)
    end
    
    def registration_changeset(user, params) do
        user
        |> changeset(params)
        |> cast(params, [:password])
        |> validate_required([:password])
        |> validate_length(:password, min: 6, max: 254)
        |> put_pass_hash
    end

    defp put_pass_hash(changeset) do
        case changeset do
            %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
                put_change(changeset, :password_hash, Pbkdf2.hash_pwd_salt(pass))
            _ ->
                changeset # return to caller is changeset is not valid
        end
    end
end

site/lib/site/application.ex
defmodule Site.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Site.Repo,
      # Start the Telemetry supervisor
      SiteWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Site.PubSub},
      # Start the Endpoint (http/https)
      SiteWeb.Endpoint
      # Start a worker by calling: Site.Worker.start_link(arg)
      # {Site.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Site.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    SiteWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

site/lib/site/repo.ex
defmodule Site.Repo do
  use Ecto.Repo,
    otp_app: :site,
    adapter: Ecto.Adapters.Postgres
end

site/lib/site_web/controllers/page_controller.ex
defmodule SiteWeb.PageController do
  use SiteWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

site/lib/site_web/controllers/session_controller.ex
defmodule SiteWeb.SessionController do
    use SiteWeb, :controller

    def new(conn, _) do
        render(conn, "new.html")
    end

    def create(conn, %{"session" => %{"userphrase" => userphrase, "passphrase" => passphrase}}) do
        case Site.Accounts.authenticate_by_userphrase_and_passphrase(userphrase, passphrase) do
            {:ok, user} ->
                conn
                |> SiteWeb.Auth.login(user)
                |> put_flash(:info, "Welcome Back!")
                |> redirect(to: Routes.page_path(conn, :index))

            {:error, _reason} ->
                conn
                |> put_flash(:error, "Invalid userphrase/passphrase combination")
                |> render("new.html")
        end
    end
end

site/lib/site_web/controllers/user_controller.ex
defmodule SiteWeb.UserController do
    use SiteWeb, :controller

    alias Site.Accounts.User
    alias Site.Accounts

    def new(conn, _params) do
        changeset = Accounts.registration_changeset(%User{}, %{})
        render(conn, "new.html", changeset: changeset)
    end

    def create(conn, %{"user" => user_params}) do
        case Accounts.register_user(user_params) do
            {:ok, user} ->
                conn
                |> SiteWeb.Auth.login(user)
                |> put_flash(:info, "Account created!")
                |> redirect(to: Routes.page_path(conn, :index))
            {:error, %Ecto.Changeset{} = changeset} ->
                render(conn, "new.html", changeset: changeset)
        end
    end
end

site/lib/site_web/views/error_view.ex
defmodule SiteWeb.ErrorView do
  use SiteWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

site/lib/site_web/views/layout_view.ex
defmodule SiteWeb.LayoutView do
  use SiteWeb, :view
end

site/lib/site_web/views/page_view.ex
defmodule SiteWeb.PageView do
  use SiteWeb, :view
end

site/lib/site_web/views/session_view.ex
defmodule SiteWeb.SessionView do
    use SiteWeb, :view
end

site/lib/site_web/views/user_view.ex
defmodule SiteWeb.UserView do
    use SiteWeb, :view
end

site/lib/site_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Site · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

site/lib/site_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace-of-mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>

site/lib/site_web/templates/session/new.html.eex
<h1> Login </h1>

<%= form_for @conn, Routes.session_path(@conn, :create), [as: :session], fn f-> %> <!-- WE are asking to submit the information inside a field called "session" -->
<!--  Not using a changeset because this data is data that doesn't go to the database-->
    <div>
        <%= text_input f, :userphrase, placeholder: "User Phrase" %>
    </div>
    <div>
        <%= password_input f, :passphrase, placeholder: "Pass Phrase" %>
    </div>

    <%= submit "Log in"%>
<% end %>

site/lib/site_web/templates/user/new.html.eex
<h1>New User</h1>

<%= if @changeset.action do %>
    <div class= "alert alert-danger">
        <p>Opps, something went wrong!</p>
    </div>
<% end %>

<%= form_for @changeset, Routes.user_path(@conn, :create), fn f-> %>
    <div>
        <%= text_input f, :userphrase, placeholder: "User Phrase"%>
        <%= error_tag f, :userphrase %>
    </div>
    <div>
        <%= text_input f, :password, placeholder: "Pass Phrase"%>
        <%= error_tag f, :password %>
    </div>
    <%= submit "Create User" %>
<% end %>